package controllers.concrete;

public enum CommandName {
	DO_AUTH, DO_REGISTRATION,
	
	GO_TO_REGISTRATION_PAGE, GO_TO_INDEX_PAGE,//
	
	GO_TO_WELCOME_PAGE,
	
	NO_SUCH_COMMAND, GO_TO_MAIN_PAGE, DO_LOGOUT,
	GO_TO_ADD_PAGE, NEWS_ADD, NEWS_REMOVE, GO_TO_USER_MANAGER, USER_ADD_PRIV, USER_PRIV_CHANGE, REMOVE_USER_FROM_BLACKLIST,
	USER_ADD_TO_BLACKLIST

}
